### PR TITLE
#186 - LENIENT mode allows GPX tags without creator attributes

### LINKED ISSUE #186: Lenient mode requires creator attribute in GPX tag
A missing `creator` attribute in the GPX tag fails despite using LENIENT mode.

Example GPX file:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1">
	<trk>
		<trkseg>
			<trkpt lat="47.1849902" lon="9.3118156"><ele>1411.7906106047938</ele><time>2018-09-30T09:43:37Z</time></trkpt>
			<trkpt lat="47.1847356" lon="9.3116516"><ele>1392.486126435269</ele><time>2018-09-30T09:44:41Z</time></trkpt>
			<trkpt lat="47.1844677" lon="9.3115969"><ele>1395.0386210201773</ele><time>2018-09-30T09:45:09Z</time></trkpt>
			<trkpt lat="47.1841943" lon="9.3116178"><ele>1399.1852111777555</ele><time>2018-09-30T09:45:39Z</time></trkpt>
			<trkpt lat="47.1839262" lon="9.311698"><ele>1400.9042412783833</ele><time>2018-09-30T09:46:06Z</time></trkpt>
			<trkpt lat="47.1836688" lon="9.3118495"><ele>1404.8712068295272</ele><time>2018-09-30T09:46:30Z</time></trkpt>
			<trkpt lat="47.1834009" lon="9.3119155"><ele>1406.7036626781644</ele><time>2018-09-30T09:46:56Z</time></trkpt>
			<trkpt lat="47.1831309" lon="9.3119291"><ele>1408.6363346678631</ele><time>2018-09-30T09:47:24Z</time></trkpt>
			<trkpt lat="47.18286" lon="9.311905"><ele>1410.9618086711207</ele><time>2018-09-30T09:47:48Z</time></trkpt>
		</trkseg>
	</trk>
</gpx>

```

### PR DESCRIPTION
**Pull request by r-follador**
Fixes #186 ; remove requireNonNull for creator attribute and add test case to differentiate LENIENT and STRICT mode.

### CODE REVIEW

File: jpx/src/main/java/io/jenetics/jpx/GPX.java [hunk 1]
```diff
@@ -322,7 +322,7 @@ private GPX(
 		final Document extensions
 	) {
 		_version = requireNonNull(version);
-		_creator = requireNonNull(creator);
+		_creator = creator;
```
Comment (jenetics) [inline jpx/src/main/java/io/jenetics/jpx/GPX.java:325]: Since the _creator_ is mandatory in the standard, it should not be possible to create an invalid `GPX` object.
```java
_creator = creator != null ? creator : _CREATOR;
```
We should also mention this behavior in the Javadoc:
```java
 * @param creator the name or URL of the software that created your GPX
 *        document. This allows others to inform the creator of a GPX
 *        instance document that fails to validate. If the {@code creator}
 *        is {@code null}, {@code "JPX - https://github.com/jenetics/jpx"}   
 *        is used instead.
```

**Review by jenetics — CHANGES_REQUESTED** [review]
@r-follador, thank you for the improvement and PR. 
Just one small comment.

File: jpx/src/main/java/io/jenetics/jpx/GPX.java (hunk 1 above)
Comment (r-follador) [reply jpx/src/main/java/io/jenetics/jpx/GPX.java:325]: I'm unsure on how to handle this.

IMO, if I read a GPX file where the Creator is missing, I prefer to have it as null (in case the presence/absence of the creator attribute will be relevant down the line). This is what the lenient/strict mode is for.

On the other I agree, when building a GPX object from scratch, a non-null, default creator value should be mandatory.

This would conform with the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle) (be conservative in what you send, be liberal in what you accept).

What are your thoughts?

Comment (jenetics) [reply jpx/src/main/java/io/jenetics/jpx/GPX.java:325]: It shouldn't matter how the `GPX` object has been created. It **must** always be valid, according to the GPX standard. Setting a default value for the creator, if it is not defined, is also the existing behavior, when creating a GPX object from scratch. And I didn't want to change this. If you want to check whether the creator were missing in the file, you can compare the creator with the default _JPX_ creator.

So, I would set the creator to a default value. Making the creator nullable would also violate the (unwritten) design principle of the library, that nullable values are represented by `Optional` classes.

Comment (r-follador) [reply jpx/src/main/java/io/jenetics/jpx/GPX.java:325]: Ok, good for me

**Review by jenetics — APPROVED** [review]
